gregsblog/gregsblog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from posts.views import PostsDetailView, PostsListView
from sitepages.views import CoverPageView

urlpatterns = [
    path("back/", admin.site.urls),
    path("home/", PostsListView.as_view(), name="home"),
    path("posts/<slug:slug>/", PostsDetailView.as_view(), name="post_detail"),
    path("", CoverPageView.as_view(), name="cover"),
    path("", include("sitepages.urls", namespace="sitepages")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gregsblog/sitepages/urls.py
from django.urls import path
from sitepages.views import (
    AboutPageView,
    CoswavesPageView,
    RainbowCirclesPageView,
    SpinstarsPageView,
    StarshowerPageView,
    SurpriseOnePageView,
    SurpriseThreePageView,
    SurpriseTwoPageView,
    TrianglesPageView,
)

app_name = "sitepages"

urlpatterns = [
    path("about/", AboutPageView.as_view(), name="about"),
    path("view1/", SurpriseOnePageView.as_view(), name="view1"),
    path("view2/", SurpriseTwoPageView.as_view(), name="view2"),
    path("view3/", SurpriseThreePageView.as_view(), name="view3"),
    path("cover_triangles/", TrianglesPageView.as_view(), name="cover_triangles"),
    path(
        "cover_rainbow_circles/",
        RainbowCirclesPageView.as_view(),
        name="cover_rainbow_circles",
    ),
    path("cover_coswaves/", CoswavesPageView.as_view(), name="cover_coswaves"),
    path("starshower/", StarshowerPageView.as_view(), name="starshower"),
    path("spinstars/", SpinstarsPageView.as_view(), name="spinstars"),
]  # type: ignore

gregsblog/posts/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from .managers import PublishedPostsManager


# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)
    pub_date = models.DateTimeField()
    image = models.ImageField(upload_to="media/")
    body = models.TextField()
    posted = models.BooleanField(
        verbose_name="Published",
        default=True,
        help_text=_(
            "Unchecking this box will put the post "
            "into draft mode and it will not appear on the site."
        ),
    )
    slug = models.SlugField(
        null=True,
        unique=True,
        max_length=50,
        help_text=_(
            "This field determines the url path of this post. "
            "It defaults to the title."
        ),
    )

    class Meta:
        ordering = ["-pub_date"]
        verbose_name = "Post"
        verbose_name_plural = "Posts"

    def __str__(self):
        return self.title

    def pub_date_pretty(self):
        return self.pub_date.strftime("%b %d %Y")

    def summary(self):
        summary = self.body[:100]
        return "{} ...".format(summary)

    objects = models.Manager()  # To eliminate local pylint errors
    published = PublishedPostsManager()

gregsblog/sitepages/models.py
from django.db import models


# Create your models here.
class Sitepages(models.Model):
    title = models.CharField(max_length=50)
    body = models.TextField()

    def __str__(self):
        return self.title

gregsblog/posts/views.py
from django.db.models import Q
from django.views.generic import DetailView, ListView

from .models import Post


class PostsListView(ListView):
    template_name = "posts/home.html"
    paginate_by = 8

    def get_queryset(self):
        query = self.request.GET.get("q")
        if query:
            return Post.published.filter(
                Q(title__icontains=query) | Q(body__icontains=query)
            )
        else:
            return Post.published.all()


class PostsDetailView(DetailView):
    queryset = Post.published.all()
    template_name = "posts/post_detail.html"

gregsblog/sitepages/views.py
from django.views.generic.base import TemplateView


class CoverPageView(TemplateView):
    template_name = "sitepages/cover.html"


class TrianglesPageView(TemplateView):
    template_name = "sitepages/cover_triangles.html"


class RainbowCirclesPageView(TemplateView):
    template_name = "sitepages/cover_rainbow_circles.html"


class CoswavesPageView(TemplateView):
    template_name = "sitepages/cover_coswaves.html"


class AboutPageView(TemplateView):
    template_name = "sitepages/about.html"


class SurpriseOnePageView(TemplateView):
    template_name = "sitepages/view1.html"


class SurpriseTwoPageView(TemplateView):
    template_name = "sitepages/view2.html"


class SurpriseThreePageView(TemplateView):
    template_name = "sitepages/view3.html"


class StarshowerPageView(TemplateView):
    template_name = "sitepages/starshower.html"


class SpinstarsPageView(TemplateView):
    template_name = "sitepages/spinstars.html"

gregsblog/posts/templates/posts/base.html
{% extends "base.html" %}

{% block content %}
{% endblock %}

gregsblog/posts/templates/posts/home.html
{% extends "posts/base.html" %}
{% block title %}Greg's Tech Blog{% endblock %}
{% block content %}
{% load static %}
{% load markdownify %}
{% load util_tags %}
{% load pagination_filter %}
  
<br>
<div class="container">
    <h1 class="text-center">Welcome to Greg's Tech Blog!</h1>
    <br />
    <br />
    
    <a href="{% url 'cover' %}">
    <img src="{% static 'posts/images/home.jpg' %}" class="img-fluid rounded mx-auto d-block" style="max-height:350px;"  /></a>
    <br />
    <h2>Latest Posts</h2>
    <hr />

    <br />
    <form class='form-inline' method="GET" action="">
        <input type='text' class='form-control mr-1' name='q' placeholder='Search Post Content'/>
        <button type="submit" class="btn btn-dark">Search</button>
    </form>
    <br />
    <br />

    {% for post in page_obj  %}

    <a href="{% url 'post_detail' post.slug %}"><h5><u>{{ post.title }}</u></h5></a>
    <br />
    <h6>{{ post.pub_date_pretty }}</h6>
    <br />
    <img src="{{ post.image.url }}" class="img-fluid rounded mx-auto d-block" style="max-height:200px;"alt="Picture here" />
    <br />
    <br />
    {{ post.summary | markdown | safe }}  <a href="{% url 'post_detail' post.slug %}">Continue Reading</a>
    <br />
    <br />
    <br />
    {% endfor %}

    {% if is_paginated %}
        <div class="text-center pb-5">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?{% param_replace page=1 %}">&laquo; First</a>
                {% if page_obj.previous_page_number != 1 %}
                    <span class="pl-4">
                    <a href="?{% param_replace page=page_obj.previous_page_number %}">Previous</a>
                    </span>
                {% endif %}
            {% endif %}
        

            <span class="current px-4">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
            </span>

            {% if page_obj.has_next %}
                {% if page_obj.next_page_number != paginator.num_pages %}
                    <span class="pr-4">
                        <a href="?{% param_replace page=page_obj.next_page_number %}">Next</a>
                    </span>
                {% endif %}
                <a href="?{% param_replace page=paginator.num_pages %}">Last &raquo;</a>
            {% endif %}
            <p>Posts {{ page_obj.start_index }} - {{ page_obj.end_index }}</p>
        </span>
        </div>
    {% endif %}
</div>
{% endblock %}



gregsblog/posts/templates/posts/post_detail.html
{% extends "posts/base.html" %}
{% block title %}Greg's Tech Blog{% endblock %}
{% block content %}
{% load static %}
{% load markdownify %}
{% load util_tags %}

<div class="container">
<br />
<br />
<h3><u>{{ object.title }}</u></h3>
{{ object.pub_date_pretty }}
<br />
<br />
<img src="{{ object.image.url }}" class="img-fluid rounded mx-auto d-block" style="max-height:450px;" alt="Picture here" />
<br />
<br />

{{ object.body | markdown | safe | linebreaks }}
<br />
<br />
<br />
      <div id="disqus_thread"></div>
      <script>

    
      var disqus_config = function () {
      this.page.identifier = 'post-{{ object.slug }}'; 
      };
     
      (function() { // DON'T EDIT BELOW THIS LINE
      var d = document, s = d.createElement('script');
      s.src = 'https://blogsight.disqus.com/embed.js';
      s.setAttribute('data-timestamp', +new Date());
      (d.head || d.body).appendChild(s);
      })();
      </script>
      <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
      
</div>
{% endblock %}

gregsblog/sitepages/templates/sitepages/about.html
{% extends "sitepages/base.html" %}
{% block title %}About The Blog{% endblock %}
{% block content %}
{% load static %}

<div class="container">
    <h1 class="text-center">About This Blog</h1>
    <br />
    <img src="{% static 'sitepages/images/about.jpg' %}" class="img-fluid rounded mx-auto d-block" style="max-height:350px;"  />
    <br />
    <br />

    <!-- Used Bootstrap columns to decrease the width of the textbox -->
    <div class="row">
        <div class="col-md-2"></div>
      <div class="col-md-8">
      <br />
    <p class="text-left">
      The inspiration for this blog project came from my desire to improve my skills in programming. The basics of it were taken from an online course taught by Nick Walter and I highly recommend his material. 
      <br />
      <br />
      This blog site was built using Django/Python, with assistance from HTML, CSS and Bootstrap. So, this was a full-stack project (of sorts) and it was certainly fun to get some exposure to both the front and back-end. 
      Ubuntu, nginx and gunicorn were used to deploy the site.
      <br />
      <br />
      Although this blog started out as a coding challenge and learning opportunity, I plan to keep the blog going with mainly programming related posts. 
      The project was a challenge at times and I will go into more detail about those challenges in some of the blog posts. Also, I hope to add functionality to the Blog itself as I improve my skills. 
      <br />
      <br />
      </p>
      <p class="text-center">Thanks for reading this far!!</p>
      <br />
      <br />

      </div>
      <div class="col-md-2"></div>
    </div>
  </div>
{% endblock %}

gregsblog/sitepages/templates/sitepages/base.html
{% extends "base.html" %}

{% block content %}
{% endblock %}

gregsblog/sitepages/templates/sitepages/cover.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Greg's Tech Blog</title>

    <link rel="stylesheet" href="{% static 'css/cover.css' %}"/>
</head>

<body>
    <canvas id="canvas">World's Hottest Blog (Nearly...)</canvas>
    <script src="{% static 'sitepages/cover.js' %}"></script>
    
    <div class="main_title">
        <a href="{% url 'home' %}" >Greg's Tech Blog</a>
        <p>Click for Night | Doubleclick for Day</p>
    </div>
</body>
</html>

gregsblog/sitepages/templates/sitepages/cover_coswaves.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Cover Coswaves</title>
    <link rel="stylesheet" href="{% static 'css/cover_coswaves.css' %}"/>
</head>

<body>
    <canvas>Your browser does not support HTML5 Canvas property.</canvas>
    <script src="{% static 'sitepages/coswaves.js' %}"></script>
    
    <div class="main_title">
        <a href="{% url 'home' %}" >Greg's Tech Blog</a>
    </div>
</body>
</html>

gregsblog/sitepages/templates/sitepages/cover_rainbow_circles.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Cover Rainbow Circles</title>
    <link rel="stylesheet" href="{% static 'css/cover_rainbow_circles.css' %}"/>
</head>

<body>
    <canvas>Your browser does not support HTML5 Canvas property.</canvas>
    <script src="{% static 'sitepages/rainbow_circles.js' %}"></script>
    
    <div class="main_title">
        <a href="{% url 'home' %}" >Greg's Tech Blog</a>
    </div>
</body>
</html>

gregsblog/sitepages/templates/sitepages/cover_triangles.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Cover Triangles</title>
    <link rel="stylesheet" href="{% static 'css/cover_triangles.css' %}"/>
</head>

<body>
    <canvas>Your browser does not support HTML5 Canvas property.</canvas>
    <script src="{% static 'sitepages/triangles.js' %}"></script>
    
    <div class="main_title">
        <a href="{% url 'home' %}" >Greg's Tech Blog</a>
        <p>Click to Restart</p>
    </div>
</body>
</html>

gregsblog/sitepages/templates/sitepages/demo.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Demo Site</title>
    <link rel="stylesheet" href="{% static 'css/demo.css' %}"/>
</head>

<body>
    <!-- Header Showcase -->
    <header id="showcase" class="grid">
        <div id="motion-picture" class="content-wrap">

            <canvas>Your browser does not support HTML5 Canvas property.</canvas>
            <script src="{% static 'sitepages/demo.js' %}"></script>
        </div>
    </header>

    <!-- Main Area -->
    <main id="main">
        <!-- Section A -->
        <section id="section-a" class="grid">
            <div id="backpic1" class="bg-image"></div>
            <div class="content-wrap">
                <h3>Come see the future!</h3>
                <p id="pitch">
                    In today's business landscape holding the attention of a consumer is a high priority.<br>
                    However, this fact can still get overlooked when a business promotes itself online, or it gets executed poorly e.g. incessant pop-ups.
                    I suggest a unique alternative or perhaps addition. A simple animation.<br> 
                    When executed well, an animation can be eye-catching, appealing and even elicit a desired emotion!
                    All these factors lead to the consumer being entertained and thus holding their attention while increasing engagement.<br> 
                    Is that it? Not by a longshot.<br>
                    I have the skills to make an animation unique to a business, place in the forefront or background of the site, and make it interactive! 
                    Interactivity can result in even more engagement...How? By making the interactivity interesting and fun.   
                </p>
            </div>
        </section>
        <!-- Section B -->
        <section id="section-b" class="grid">
            <ul>
                <li>
                    <div id="card">
                        <img id="im1" src="../../static/sitepages/images/lumi.jpg" alt="Image1">
                        <div class="card-content">
                            <h3 class="card-title">Ideas</h3>
                            <p>"Think more thoughtfully" <p id="quoter">- Daniel Shiffman</p></p>
                        </div>
                    </div>
                </li>
                <li>
                    <div id="card">
                        <img id="im2" src="../../static/sitepages/images/thumb.jpg" alt="Image2">
                        <div class="card-content">
                            <h3 class="card-title">Success</h3>
                            <p>"Anything less isn't success" <p title="Actually me as far as I know" id="quoter">- Anonymous</p></p>
                        </div>
                    </div>
                </li>
                <li>
                    <div id="card">
                        <img id="im3" src="../../static/sitepages/images/pen.jpg" alt="Image3">
                        <div class="card-content">
                            <h3 class="card-title">See Above</h3>
                            <p>"Creating something is more difficult than destroying something, but is ultimately more rewarding." <p title="Actually me as far as I know" id="quoter">- Anonymous</p></p>
                        </div>
                    </div>
                </li>
            </ul>
        </section>

        <!-- Section C -->
        <section id="section-c" class="grid">
            <div id="backpic2" class="bg-image"></div>
            <div class="content-wrap">
                <h2>Experience the possibilities offered by animated interactive design</h2>
            </div>
            
        </section>

        <!-- Section D -->
        <section id="section-d" class="grid">
            <div class="box">
                <h2>Contact</h2>
                <p>webdevchev@gmail.com</p>
            </div>
            <div class="box">
                <h2 class="content-title">About</h2>
                <p>I made this website as a means of providing a quick demostration of my skills.<br>
                    The message above is sincere and relevent, however, this project should not be viewed as something that seriously promotes my business 
                    (I haven't gone live with that site yet) but rather, as mentioned, a demostration of skills.
                    Some of the things I'd like to point out are:<br> 
                    1) The JavaScript animation in the header.<br>
                    2) The mobile friendly nature of site done with CSS3 grids (make the view window narrower and hit refresh to see the difference if you're viewing on a computer monitor).<br>
                    3) The backround parallax patterns and colour design of the website. 
                </p>
            </div>
        </section>
    </main>

    <!-- Footer -->
    <footer id="main-footer" class="grid">
        <div>Vandelay Industries</div>
        <div> 
            <a id="button" href="#" onclick="return false" onmousedown="autoScrollTo();" class="btn">Back to Top</a>
        </div>
        <div>Browse the <a href="http://gregsukochev.net">Tech Blog</a></div>
    </footer>
</body>

</html>

gregsblog/sitepages/templates/sitepages/practice.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Practice</title>
    <link rel="stylesheet"  href="../../static/sitepages/style.css">
</head>
<body>
    

</div>

    <canvas>Your browser does not support HTML5 Canvas property.</canvas>
        <script src="{% static 'sitepages/practice.js' %}"></script>

    <div class="main_title">
        <a href="{% url 'home' %}" >Greg's Tech Blog</a>
    </div>

</body>
</html>

gregsblog/sitepages/templates/sitepages/spinstars.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Spin-Stars</title>
    <link rel="stylesheet" href="{% static 'css/spinstars.css' %}"/>
</head>
<body>
 <!--I wanted to create some clouds to make it look a little less stale, pictures were drawn by me in GIMP  -->
<div class="container">
    <div class="cloud1"><img src="{% static 'sitepages/images/Cloud3c.png' %}"></div>
    <div class="cloud3"><img src="{% static 'sitepages/images/Cloud3c.png' %}"></div>
    <div class="cloud2"><img src="{% static 'sitepages/images/Cloud3c.png' %}"></div>

</div>

    <canvas>Your browser does not support HTML5 Canvas property.</canvas>
        <script src="{% static 'sitepages/spinstars.js' %}"></script>

    <div class="main_title">
        <a href="{% url 'home' %}" >Greg's Tech Blog</a>
        <p>Click to Spin | Spin to Win</p>
        
    </div>

</body>
</html>

gregsblog/sitepages/templates/sitepages/starshower.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Starshower</title>
    <link rel="stylesheet" href="{% static 'css/starshower.css' %}"/>
</head>
<body>
    <canvas id="canvas">Your browser does not support HTML5 Canvas property.</canvas>
    <script src="{% static 'sitepages/starshower.js' %}"></script>

    <div class="main_title">
        <a href="{% url 'home' %}" >Greg's Tech Blog</a>
    </div>
</body>
</html>

gregsblog/sitepages/templates/sitepages/view1.html
{% extends "sitepages/base.html" %}
{% block title %}Greg's Tech Blog{% endblock %}
{% block content %}
{% load static %}         

<div class="container">
<br />
    <h1 class="text-center">Surprise</h1>
    <br />
    <img src="{% static 'sitepages/images/surprise.jpg' %}" class="img-fluid rounded mx-auto d-block" style="max-height:350px;"  />

    <br />
    <br />
    <p>
        You made it to this particular Surprise page, but there is a chance you will get diverted to other pages if you click the "Surprise" button again!.
        <br />
        This is Surprise page 1!!! Enjoy!
    </p>

  </div>
{% endblock %}

gregsblog/sitepages/templates/sitepages/view2.html
{% extends "sitepages/base.html" %}
{% block title %}Greg's Tech Blog{% endblock %}
{% block content %}
{% load static %}

<div class="container">
<br />
    <h1 class="text-center">Surprise II</h1>
    <br />
    <img src="{% static 'sitepages/images/surprise2.png' %}" class="img-fluid rounded mx-auto d-block" style="max-height:350px;"  />

    <br />
    <br />
    <p>
        You made it to this particular Surprise page, but there is a chance you will get diverted to other pages if you click the "Surprise" button again!.
        <br />
        This is Surprise page 2!! Admittedly not much different from the other two pages, but still kind of interesting.
    </p>

  </div>
{% endblock %}

  

gregsblog/sitepages/templates/sitepages/view3.html
{% extends "sitepages/base.html" %}
{% block title %}Greg's Tech Blog{% endblock %}
{% block content %}
{% load static %}       


<div class="container">
<br />
    <h1 class="text-center">Surprise III</h1>
    <br />
    
    <img src="{% static 'sitepages/images/surprise3.jpg' %}" class="img-fluid rounded mx-auto d-block" style="max-height:350px;"  />

    <br />
    <br />
    <p>
        You made it to this particular Surprise page, but there is a chance you will get diverted to other pages if you click the "Surprise" button again!.
        <br />
        This is Page 3!! Again, not very different from the other two pages, but still kind of interesting.
    </p>
  </div>
{% endblock %}

gregsblog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

    <title>{% block title %}Greg's Tech Blog{% endblock %}</title>
  </head>
  <body>
      {% load markdownify %}
      {% load util_tags %} 
      <!-- Nav Bar done with Bootsrap -->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                </button>
                <a class="navbar-brand" href="{% url 'home' %}">Greg's Tech Blog</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                  <div class="navbar-nav">
                    <a class="nav-item nav-link active" href="{% url 'sitepages:about' %}">About</a>
                    <a class="nav-item nav-link" href="https://en.wikipedia.org/wiki/Grigory_Sukochev">Wiki</a>
                    <a class="nav-item nav-link" href="{% random_url %}">Surprise</a>
                    <a class="nav-item nav-link active" href="http://149.28.175.75/" target="_blank">Number Quest</a>
                    <div class="dropdown">
                        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Cover Pages
                          </button>
                          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item" href="{% url 'sitepages:spinstars' %}">Spin-Stars</a>
                            <a class="dropdown-item" href="{% url 'sitepages:starshower' %}">Starshower</a>
                            <a class="dropdown-item" href="{% url 'sitepages:cover_triangles' %}">Triangles</a>
                            <a class="dropdown-item" href="{% url 'sitepages:cover_coswaves' %}">Sinewaves</a>
                            
                          </div>
                    </div>
                  </div>
                </div>
              </nav>
    {% block content %}
    {% endblock %}
              


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
  </body>
</html>